import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { GridBackgroundDemo } from "./components/ui/GridBackground";

import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
    <html lang="en" className="dark">
      <body className={inter.className}>
        <GridBackgroundDemo>
        {children}
        </GridBackgroundDemo>
        </body>
    </html>
    </ClerkProvider>
  );
}
